name: paysmart_app
description: A patched PaySmart app
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.0
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.0
  google_fonts: any
