name: paysmart_app
description: A Smart Payment & Rewards App (Flutter skeleton)
version: 0.1.0+1
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  dio: ^5.4.3
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  animated_bottom_navigation_bar: ^1.3.3
  lottie: ^3.1.2
  firebase_messaging: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/